// 타입 지정

export interface CStypes {
  [x: string]: string[];
}

const championSynergy: CStypes = {
  Galio: ["거신", "사교계", "경호대"],
  Gangplank: ["용병", "쌍발총"],
  Gnar: ["사교계", "요들", "타격대"],
  Nocturne: ["마법공학", "암살자"],
  Darius: ["범죄조직", "경호대"],
  Draven: ["연미복"],
  Renata: ["화학공학", "학자"],
  Leona: ["연미복", "경호대"],
  RekSai: ["돌연변이", "난동꾼", "타격대"],
  Lucian: ["마법공학", "쌍발총"],
  Lulu: ["요들", "강화술사"],
  Malzahar: ["돌연변이", "비전마법사"],
  Morgana: ["범죄조직", "강화술사"],
  MissFortune: ["용병", "저격수"],
  Vi: ["경쟁자", "집행자", "난동꾼"],
  Veigar: ["요들군주"],
  Vex: ["요들", "비전마법사"],
  Braum: ["범죄조직", "경호대"],
  Brand: ["연미복", "비전마법사"],
  Blitzcrank: ["고물상", "경호대"],
  Viktor: ["화학공학", "비전마법사"],
  Poppy: ["요들", "경호대"],
  Senna: ["사교계", "강화술사"],
  Seraphine: ["사교계", "혁신가"],
  Sejuani: ["마법공학", "집행자", "난동꾼"],
  Swain: ["마법공학", "비전마법사"],
  Sivir: ["마법공학", "타격대"],
  Syndra: ["연미복", "학자"],
  Singed: ["화학공학", "혁신가"],
  Silco: ["흑막", "학자"],
  Ahri: ["범죄조직", "비전마법사"],
  Alistar: ["마법공학", "거신"],
  Ashe: ["범죄조직", "저격수"],
  Ekko: ["고물상", "암살자", "혁신가"],
  Orianna: ["시계태엽", "강화술사"],
  Warwick: ["화학공학", "도전자"],
  Irelia: ["고물상", "타격대"],
  Ezreal: ["고물상", "혁신가"],
  Illaoi: ["용병", "난동꾼"],
  JarvanIV: ["마법공학", "타격대"],
  Zyra: ["범죄조직", "학자"],
  Zac: ["화학공학", "난동꾼"],
  Zeri: ["연미복", "저격수"],
  Jayce: ["집행자", "변형술사", "혁신가"],
  Ziggs: ["고물상", "요들", "비전마법사"],
  Jhin: ["시계태엽", "저격수"],
  Zilean: ["시계태엽", "혁신가"],
  Jinx: ["경쟁자", "고물상", "쌍발총"],
  Chogath: ["돌연변이", "거신", "난동꾼"],
  Camille: ["시계태엽", "도전자"],
  Kassadin: ["돌연변이", "학자"],
  Kaisa: ["돌연변이", "도전자"],
  Khazix: ["돌연변이", "암살자"],
  Caitlyn: ["집행자", "저격수"],
  Corki: ["요들", "쌍발총"],
  Quinn: ["용병", "도전자"],
  Talon: ["연미복", "암살자"],
  TahmKench: ["대식가", "용병", "난동꾼"],
  Tryndamere: ["화학공학", "도전자"],
  Twitch: ["화학공학", "암살자"],
};

export default championSynergy;
