import React from "react";
import { RecoilRoot } from "recoil";

import styles from "./App.module.scss";

import SynergyBox from "./components/SynergyBox/SynergyBox";
import SelectedBox from "./components/SelectedBox/SelectedBox";
import ChampionBox from "./components/ChampionBox/ChampionBox";
import SnyergyList from "./components/synergyList/SynergyList";

import championImgUrl from "./staticStore/champion_img_url";
import synergy_svg_url from "./staticStore/synergy_svg_url";
import championSynergy from "./staticStore/championSynergy";

function App() {
  return (
    <RecoilRoot>
      <div className={styles["App"]}>
        <SelectedBox></SelectedBox>
        <SnyergyList />
        {/* 경쟁자 */}
        <SynergyBox name="경쟁자" enName="Rival" url={synergy_svg_url.Rival}>
          <ChampionBox
            name="Vi"
            cost={4}
            url={championImgUrl.Vi}
            synergy={championSynergy.Vi}
          />
          <ChampionBox
            name="Jinx"
            cost={5}
            url={championImgUrl.Jinx}
            synergy={championSynergy.Jinx}
          />
        </SynergyBox>
        {/* 고물상 */}
        <SynergyBox name="고물상" enName="Scrap" url={synergy_svg_url.Scrap}>
          <ChampionBox
            name="Ezreal"
            cost={1}
            url={championImgUrl.Ezreal}
            synergy={championSynergy.Ezreal}
          />
          <ChampionBox
            name="Ziggs"
            cost={1}
            url={championImgUrl.Ziggs}
            synergy={championSynergy.Ziggs}
          />
          <ChampionBox
            name="Blitzcrank"
            cost={2}
            url={championImgUrl.Blitzcrank}
            synergy={championSynergy.Blitzcrank}
          />
          <ChampionBox
            name="Ekko"
            cost={3}
            url={championImgUrl.Ekko}
            synergy={championSynergy.Ekko}
          />
          <ChampionBox
            name="Irelia"
            cost={4}
            url={championImgUrl.Irelia}
            synergy={championSynergy.Irelia}
          />
          <ChampionBox
            name="Jinx"
            cost={5}
            url={championImgUrl.Jinx}
            synergy={championSynergy.Jinx}
          />
        </SynergyBox>
        {/* 대식가 */}
        <SynergyBox
          name="대식가"
          enName="Glutton"
          url={synergy_svg_url.Glutton}
        >
          <ChampionBox
            name="TahmKench"
            cost={1}
            url={championImgUrl.TahmKench}
            synergy={championSynergy.TahmKench}
          />
        </SynergyBox>
        {/* 돌연변이 */}
        <SynergyBox
          name="돌연변이"
          enName="Mutant"
          url={synergy_svg_url.Mutant}
        >
          <ChampionBox
            name="Kassadin"
            cost={1}
            url={championImgUrl.Kassadin}
            synergy={championSynergy.Kassadin}
          />
          <ChampionBox
            name="RekSai"
            cost={2}
            url={championImgUrl.RekSai}
            synergy={championSynergy.RekSai}
          />
          <ChampionBox
            name="Malzahar"
            cost={3}
            url={championImgUrl.Malzahar}
            synergy={championSynergy.Malzahar}
          />
          <ChampionBox
            name="Chogath"
            cost={3}
            url={championImgUrl.Chogath}
            synergy={championSynergy.Chogath}
          />
          <ChampionBox
            name="Khazix"
            cost={4}
            url={championImgUrl.Khazix}
            synergy={championSynergy.Khazix}
          />
          <ChampionBox
            name="Kaisa"
            cost={5}
            url={championImgUrl.Kaisa}
            synergy={championSynergy.Kaisa}
          />
        </SynergyBox>
        {/* 마법공학 */}
        <SynergyBox
          name="마법공학"
          enName="Hextech"
          url={synergy_svg_url.Hextech}
        >
          <ChampionBox
            name="Nocturne"
            cost={1}
            url={championImgUrl.Nocturne}
            synergy={championSynergy.Nocturne}
          />
          <ChampionBox
            name="JarvanIV"
            cost={1}
            url={championImgUrl.JarvanIV}
            synergy={championSynergy.JarvanIV}
          />
          <ChampionBox
            name="Sejuani"
            cost={2}
            url={championImgUrl.Sejuani}
            synergy={championSynergy.Sejuani}
          />
          <ChampionBox
            name="Swain"
            cost={2}
            url={championImgUrl.Swain}
            synergy={championSynergy.Swain}
          />
          <ChampionBox
            name="Lucian"
            cost={3}
            url={championImgUrl.Lucian}
            synergy={championSynergy.Lucian}
          />
          <ChampionBox
            name="Sivir"
            cost={4}
            url={championImgUrl.Sivir}
            synergy={championSynergy.Sivir}
          />
          <ChampionBox
            name="Alistar"
            cost={4}
            url={championImgUrl.Alistar}
            synergy={championSynergy.Alistar}
          />
        </SynergyBox>
        {/* 범죄조직 */}
        <SynergyBox
          name="범죄조직"
          enName="Syndicate"
          url={synergy_svg_url.Syndicate}
        >
          <ChampionBox
            name="Darius"
            cost={1}
            url={championImgUrl.Darius}
            synergy={championSynergy.Darius}
          />
          <ChampionBox
            name="Ashe"
            cost={2}
            url={championImgUrl.Ashe}
            synergy={championSynergy.Ashe}
          />
          <ChampionBox
            name="Zyra"
            cost={2}
            url={championImgUrl.Zyra}
            synergy={championSynergy.Zyra}
          />
          <ChampionBox
            name="Morgana"
            cost={3}
            url={championImgUrl.Morgana}
            synergy={championSynergy.Morgana}
          />
          <ChampionBox
            name="Braum"
            cost={4}
            url={championImgUrl.Braum}
            synergy={championSynergy.Braum}
          />
          <ChampionBox
            name="Ahri"
            cost={4}
            url={championImgUrl.Ahri}
            synergy={championSynergy.Ahri}
          />
        </SynergyBox>
        {/* 사교계 */}
        <SynergyBox
          name="사교계"
          enName="Sociallite"
          url={synergy_svg_url.Socialite}
        >
          <ChampionBox
            name="Gnar"
            cost={3}
            url={championImgUrl.Gnar}
            synergy={championSynergy.Gnar}
          />
          <ChampionBox
            name="Senna"
            cost={3}
            url={championImgUrl.Senna}
            synergy={championSynergy.Senna}
          />
          <ChampionBox
            name="Seraphine"
            cost={4}
            url={championImgUrl.Seraphine}
            synergy={championSynergy.Seraphine}
          />
          <ChampionBox
            name="Galio"
            cost={5}
            url={championImgUrl.Galio}
            synergy={championSynergy.Galio}
          />
        </SynergyBox>
        {/* 시계태엽 */}
        <SynergyBox
          name="시계태엽"
          enName="Clockwork"
          url={synergy_svg_url.Clockwork}
        >
          <ChampionBox
            name="Camille"
            cost={1}
            url={championImgUrl.Camille}
            synergy={championSynergy.Camille}
          />
          <ChampionBox
            name="Zilean"
            cost={2}
            url={championImgUrl.Zilean}
            synergy={championSynergy.Zilean}
          />
          <ChampionBox
            name="Orianna"
            cost={4}
            url={championImgUrl.Orianna}
            synergy={championSynergy.Orianna}
          />
          <ChampionBox
            name="Jhin"
            cost={4}
            url={championImgUrl.Jhin}
            synergy={championSynergy.Jhin}
          />
        </SynergyBox>
        {/* 연미복 */}
        <SynergyBox
          name="연미복"
          enName="Debonair"
          url={synergy_svg_url.Debonair}
        >
          <ChampionBox
            name="Brand"
            cost={1}
            url={championImgUrl.Brand}
            synergy={championSynergy.Brand}
          />
          <ChampionBox
            name="Syndra"
            cost={2}
            url={championImgUrl.Syndra}
            synergy={championSynergy.Syndra}
          />
          <ChampionBox
            name="Talon"
            cost={2}
            url={championImgUrl.Talon}
            synergy={championSynergy.Talon}
          />
          <ChampionBox
            name="Leona"
            cost={3}
            url={championImgUrl.Leona}
            synergy={championSynergy.Leona}
          />
          <ChampionBox
            name="Draven"
            cost={4}
            url={championImgUrl.Draven}
            synergy={championSynergy.Draven}
          />
          <ChampionBox
            name="Zeri"
            cost={5}
            url={championImgUrl.Zeri}
            synergy={championSynergy.Zeri}
          />
        </SynergyBox>
        {/* 요들 */}
        <SynergyBox name="요들" enName="Yordle" url={synergy_svg_url.Yordle}>
          <ChampionBox
            name="Poppy"
            cost={1}
            url={championImgUrl.Poppy}
            synergy={championSynergy.Poppy}
          />
          <ChampionBox
            name="Ziggs"
            cost={1}
            url={championImgUrl.Ziggs}
            synergy={championSynergy.Ziggs}
          />
          <ChampionBox
            name="Lulu"
            cost={2}
            url={championImgUrl.Lulu}
            synergy={championSynergy.Lulu}
          />
          <ChampionBox
            name="Corki"
            cost={2}
            url={championImgUrl.Corki}
            synergy={championSynergy.Corki}
          />
          <ChampionBox
            name="Gnar"
            cost={3}
            url={championImgUrl.Gnar}
            synergy={championSynergy.Gnar}
          />
          <ChampionBox
            name="Vex"
            cost={3}
            url={championImgUrl.Vex}
            synergy={championSynergy.Vex}
          />
        </SynergyBox>
        {/* 요들군주 */}
        <SynergyBox
          name="요들군주"
          enName="YordleLord"
          url={synergy_svg_url.Yordle}
        >
          <ChampionBox
            name="Veigar"
            cost={5}
            url={championImgUrl.Veigar}
            synergy={championSynergy.Veigar}
          />
        </SynergyBox>
        {/* 용병 */}
        <SynergyBox
          name="용병"
          enName="Mercenary"
          url={synergy_svg_url.Mercenary}
        >
          <ChampionBox
            name="Illaoi"
            cost={1}
            url={championImgUrl.Illaoi}
            synergy={championSynergy.Illaoi}
          />
          <ChampionBox
            name="Quinn"
            cost={2}
            url={championImgUrl.Quinn}
            synergy={championSynergy.Quinn}
          />
          <ChampionBox
            name="Gangplank"
            cost={3}
            url={championImgUrl.Gangplank}
            synergy={championSynergy.Gangplank}
          />
          <ChampionBox
            name="MissFortune"
            cost={3}
            url={championImgUrl.MissFortune}
            synergy={championSynergy.MissFortune}
          />
          <ChampionBox
            name="TahmKench"
            cost={5}
            url={championImgUrl.TahmKench}
            synergy={championSynergy.TahmKench}
          />
        </SynergyBox>
        {/* 집행자 */}
        <SynergyBox
          name="집행자"
          enName="Enforcer"
          url={synergy_svg_url.Enforcer}
        >
          <ChampionBox
            name="Caitlyn"
            cost={1}
            url={championImgUrl.Caitlyn}
            synergy={championSynergy.Caitlyn}
          />
          <ChampionBox
            name="Sejuani"
            cost={2}
            url={championImgUrl.Sejuani}
            synergy={championSynergy.Sejuani}
          />
          <ChampionBox
            name="Vi"
            cost={4}
            url={championImgUrl.Vi}
            synergy={championSynergy.Vi}
          />
          <ChampionBox
            name="Jayce"
            cost={5}
            url={championImgUrl.Jayce}
            synergy={championSynergy.Jayce}
          />
        </SynergyBox>
        {/* 화학공학 */}
        <SynergyBox
          name="화학공학"
          enName="Chemtech"
          url={synergy_svg_url.Chemtech}
        >
          <ChampionBox
            name="Singed"
            cost={1}
            url={championImgUrl.Singed}
            synergy={championSynergy.Singed}
          />
          <ChampionBox
            name="Twitch"
            cost={1}
            url={championImgUrl.Twitch}
            synergy={championSynergy.Twitch}
          />
          <ChampionBox
            name="Warwick"
            cost={2}
            url={championImgUrl.Warwick}
            synergy={championSynergy.Warwick}
          />
          <ChampionBox
            name="Zac"
            cost={3}
            url={championImgUrl.Zac}
            synergy={championSynergy.Zac}
          />
          <ChampionBox
            name="Tryndamere"
            cost={3}
            url={championImgUrl.Tryndamere}
            synergy={championSynergy.Tryndamere}
          />
          <ChampionBox
            name="Renata"
            cost={4}
            url={championImgUrl.Renata}
            synergy={championSynergy.Renata}
          />
          <ChampionBox
            name="Viktor"
            cost={5}
            url={championImgUrl.Viktor}
            synergy={championSynergy.Viktor}
          />
        </SynergyBox>
        {/* 흑막 */}
        <SynergyBox
          name="흑막"
          enName="Mastermind"
          url={synergy_svg_url.Mastermind}
        >
          <ChampionBox
            name="Silco"
            cost={5}
            url={championImgUrl.Silco}
            synergy={championSynergy.Silco}
          />
        </SynergyBox>
        {/* 강화술사 */}
        <SynergyBox
          name="강화술사"
          enName="Enchanter"
          url={synergy_svg_url.Enchanter}
        >
          <ChampionBox
            name="Lulu"
            cost={2}
            url={championImgUrl.Lulu}
            synergy={championSynergy.Lulu}
          />
          <ChampionBox
            name="Morgana"
            cost={3}
            url={championImgUrl.Morgana}
            synergy={championSynergy.Morgana}
          />
          <ChampionBox
            name="Senna"
            cost={3}
            url={championImgUrl.Senna}
            synergy={championSynergy.Senna}
          />
          <ChampionBox
            name="Orianna"
            cost={4}
            url={championImgUrl.Orianna}
            synergy={championSynergy.Orianna}
          />
        </SynergyBox>
        {/* 거신 */}
        <SynergyBox
          name="거신"
          enName="Colossus"
          url={synergy_svg_url.Colossus}
        >
          <ChampionBox
            name="Chogath"
            cost={3}
            url={championImgUrl.Chogath}
            synergy={championSynergy.Chogath}
          />
          <ChampionBox
            name="Alistar"
            cost={4}
            url={championImgUrl.Alistar}
            synergy={championSynergy.Alistar}
          />
          <ChampionBox
            name="Galio"
            cost={3}
            url={championImgUrl.Galio}
            synergy={championSynergy.Galio}
          />
        </SynergyBox>
        {/* 경호대 */}
        <SynergyBox
          name="경호대"
          enName="Bodyguard"
          url={synergy_svg_url.Bodyguard}
        >
          <ChampionBox
            name="Darius"
            cost={1}
            url={championImgUrl.Darius}
            synergy={championSynergy.Darius}
          />
          <ChampionBox
            name="Poppy"
            cost={1}
            url={championImgUrl.Poppy}
            synergy={championSynergy.Poppy}
          />
          <ChampionBox
            name="Blitzcrank"
            cost={2}
            url={championImgUrl.Blitzcrank}
            synergy={championSynergy.Blitzcrank}
          />
          <ChampionBox
            name="Leona"
            cost={3}
            url={championImgUrl.Leona}
            synergy={championSynergy.Leona}
          />
          <ChampionBox
            name="Braum"
            cost={4}
            url={championImgUrl.Braum}
            synergy={championSynergy.Braum}
          />
          <ChampionBox
            name="Galio"
            cost={5}
            url={championImgUrl.Galio}
            synergy={championSynergy.Galio}
          />
        </SynergyBox>
        {/* 난동꾼 */}
        <SynergyBox
          name="난동꾼"
          enName="Bruiser"
          url={synergy_svg_url.Bruiser}
        >
          <ChampionBox
            name="Illaoi"
            cost={1}
            url={championImgUrl.Illaoi}
            synergy={championSynergy.Illaoi}
          />
          <ChampionBox
            name="RekSai"
            cost={2}
            url={championImgUrl.RekSai}
            synergy={championSynergy.RekSai}
          />
          <ChampionBox
            name="Sejuani"
            cost={2}
            url={championImgUrl.Sejuani}
            synergy={championSynergy.Sejuani}
          />
          <ChampionBox
            name="Zac"
            cost={3}
            url={championImgUrl.Zac}
            synergy={championSynergy.Zac}
          />
          <ChampionBox
            name="Chogath"
            cost={3}
            url={championImgUrl.Chogath}
            synergy={championSynergy.Chogath}
          />
          <ChampionBox
            name="Vi"
            cost={4}
            url={championImgUrl.Vi}
            synergy={championSynergy.Vi}
          />
          <ChampionBox
            name="TahmKench"
            cost={5}
            url={championImgUrl.TahmKench}
            synergy={championSynergy.TahmKench}
          />
        </SynergyBox>
        {/* 도전자 */}
        <SynergyBox
          name="도전자"
          enName="Challenger"
          url={synergy_svg_url.Bruiser}
        >
          <ChampionBox
            name="Camille"
            cost={1}
            url={championImgUrl.Camille}
            synergy={championSynergy.Camille}
          />
          <ChampionBox
            name="Warwick"
            cost={2}
            url={championImgUrl.Warwick}
            synergy={championSynergy.Warwick}
          />
          <ChampionBox
            name="Quinn"
            cost={2}
            url={championImgUrl.Quinn}
            synergy={championSynergy.Quinn}
          />
          <ChampionBox
            name="Tryndamere"
            cost={3}
            url={championImgUrl.Tryndamere}
            synergy={championSynergy.Tryndamere}
          />
          <ChampionBox
            name="Draven"
            cost={4}
            url={championImgUrl.Draven}
            synergy={championSynergy.Draven}
          />
          <ChampionBox
            name="Kaisa"
            cost={5}
            url={championImgUrl.Kaisa}
            synergy={championSynergy.Kaisa}
          />
          <ChampionBox
            name="TahmKench"
            cost={5}
            url={championImgUrl.TahmKench}
            synergy={championSynergy.TahmKench}
          />
        </SynergyBox>
        {/* 변형술사 */}
        <SynergyBox
          name="변형술사"
          enName="Transformer"
          url={synergy_svg_url.Transformer}
        >
          <ChampionBox
            name="Jayce"
            cost={5}
            url={championImgUrl.Jayce}
            synergy={championSynergy.Jayce}
          />
        </SynergyBox>
        {/* 비전 마법사 */}
        <SynergyBox
          name="비전 마법사"
          enName="Arcanist"
          url={synergy_svg_url.Arcanist}
        >
          <ChampionBox
            name="Brand"
            cost={1}
            url={championImgUrl.Brand}
            synergy={championSynergy.Brand}
          />
          <ChampionBox
            name="Ziggs"
            cost={1}
            url={championImgUrl.Ziggs}
            synergy={championSynergy.Ziggs}
          />
          <ChampionBox
            name="Swain"
            cost={2}
            url={championImgUrl.Swain}
            synergy={championSynergy.Swain}
          />
          <ChampionBox
            name="Malzahar"
            cost={3}
            url={championImgUrl.Malzahar}
            synergy={championSynergy.Malzahar}
          />
          <ChampionBox
            name="Vex"
            cost={3}
            url={championImgUrl.Vex}
            synergy={championSynergy.Vex}
          />
          <ChampionBox
            name="Ahri"
            cost={4}
            url={championImgUrl.Ahri}
            synergy={championSynergy.Ahri}
          />
          <ChampionBox
            name="Viktor"
            cost={5}
            url={championImgUrl.Viktor}
            synergy={championSynergy.Viktor}
          />
        </SynergyBox>
        {/* 쌍발총 */}
        <SynergyBox
          name="쌍발총"
          enName="Twinshot"
          url={synergy_svg_url.Twinshot}
        >
          <ChampionBox
            name="Corki"
            cost={2}
            url={championImgUrl.Corki}
            synergy={championSynergy.Corki}
          />
          <ChampionBox
            name="Gangplank"
            cost={3}
            url={championImgUrl.Gangplank}
            synergy={championSynergy.Gangplank}
          />
          <ChampionBox
            name="Lucian"
            cost={3}
            url={championImgUrl.Lucian}
            synergy={championSynergy.Lucian}
          />
          <ChampionBox
            name="Jinx"
            cost={5}
            url={championImgUrl.Jinx}
            synergy={championSynergy.Jinx}
          />
        </SynergyBox>
        {/* 암살자 */}
        <SynergyBox
          name="암살자"
          enName="Assassin"
          url={synergy_svg_url.Assassin}
        >
          <ChampionBox
            name="Nocturne"
            cost={1}
            url={championImgUrl.Nocturne}
            synergy={championSynergy.Nocturne}
          />
          <ChampionBox
            name="Twitch"
            cost={1}
            url={championImgUrl.Twitch}
            synergy={championSynergy.Twitch}
          />
          <ChampionBox
            name="Talon"
            cost={2}
            url={championImgUrl.Talon}
            synergy={championSynergy.Talon}
          />
          <ChampionBox
            name="Ekko"
            cost={3}
            url={championImgUrl.Ekko}
            synergy={championSynergy.Ekko}
          />
          <ChampionBox
            name="Khazix"
            cost={4}
            url={championImgUrl.Khazix}
            synergy={championSynergy.Khazix}
          />
        </SynergyBox>
        {/* 저격수 */}
        <SynergyBox name="저격수" enName="Sniper" url={synergy_svg_url.Sniper}>
          <ChampionBox
            name="Caitlyn"
            cost={1}
            url={championImgUrl.Caitlyn}
            synergy={championSynergy.Caitlyn}
          />
          <ChampionBox
            name="Ashe"
            cost={2}
            url={championImgUrl.Ashe}
            synergy={championSynergy.Ashe}
          />
          <ChampionBox
            name="MissFortune"
            cost={3}
            url={championImgUrl.MissFortune}
            synergy={championSynergy.MissFortune}
          />
          <ChampionBox
            name="Jhin"
            cost={4}
            url={championImgUrl.Jhin}
            synergy={championSynergy.Jhin}
          />
          <ChampionBox
            name="Zeri"
            cost={5}
            url={championImgUrl.Zeri}
            synergy={championSynergy.Zeri}
          />
        </SynergyBox>
        {/* 타격대 */}
        <SynergyBox
          name="타격대"
          enName="Striker"
          url={synergy_svg_url.Striker}
        >
          <ChampionBox
            name="JarvanIV"
            cost={1}
            url={championImgUrl.JarvanIV}
            synergy={championSynergy.JarvanIV}
          />
          <ChampionBox
            name="RekSai"
            cost={2}
            url={championImgUrl.RekSai}
            synergy={championSynergy.RekSai}
          />
          <ChampionBox
            name="Gnar"
            cost={3}
            url={championImgUrl.Gnar}
            synergy={championSynergy.Gnar}
          />
          <ChampionBox
            name="Sivir"
            cost={4}
            url={championImgUrl.Sivir}
            synergy={championSynergy.Sivir}
          />
          <ChampionBox
            name="Irelia"
            cost={5}
            url={championImgUrl.Irelia}
            synergy={championSynergy.Irelia}
          />
        </SynergyBox>
        {/* 학자 */}
        <SynergyBox name="학자" enName="Scholar" url={synergy_svg_url.Scholar}>
          <ChampionBox
            name="Kassadin"
            cost={1}
            url={championImgUrl.Kassadin}
            synergy={championSynergy.Kassadin}
          />
          <ChampionBox
            name="Syndra"
            cost={2}
            url={championImgUrl.Syndra}
            synergy={championSynergy.Syndra}
          />
          <ChampionBox
            name="Zyra"
            cost={3}
            url={championImgUrl.Zyra}
            synergy={championSynergy.Zyra}
          />
          <ChampionBox
            name="Renata"
            cost={4}
            url={championImgUrl.Renata}
            synergy={championSynergy.Renata}
          />
          <ChampionBox
            name="Silco"
            cost={5}
            url={championImgUrl.Silco}
            synergy={championSynergy.Silco}
          />
        </SynergyBox>
        {/* 혁신가 */}
        <SynergyBox
          name="혁신가"
          enName="Innovator"
          url={synergy_svg_url.Innovator}
        >
          <ChampionBox
            name="Singed"
            cost={1}
            url={championImgUrl.Singed}
            synergy={championSynergy.Singed}
          />
          <ChampionBox
            name="Ezreal"
            cost={1}
            url={championImgUrl.Ezreal}
            synergy={championSynergy.Ezreal}
          />
          <ChampionBox
            name="Zilean"
            cost={2}
            url={championImgUrl.Zilean}
            synergy={championSynergy.Zilean}
          />
          <ChampionBox
            name="Ekko"
            cost={3}
            url={championImgUrl.Ekko}
            synergy={championSynergy.Ekko}
          />
          <ChampionBox
            name="Seraphine"
            cost={4}
            url={championImgUrl.Seraphine}
            synergy={championSynergy.Seraphine}
          />
          <ChampionBox
            name="Jayce"
            cost={5}
            url={championImgUrl.Jayce}
            synergy={championSynergy.Jayce}
          />
        </SynergyBox>
      </div>
    </RecoilRoot>
  );
}

export default App;
